//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFirstEntityTesting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentedMovies
    {
        public int RMID { get; set; }
        public Nullable<int> MovieIDFK { get; set; }
        public Nullable<int> CustIDFK { get; set; }
        public Nullable<System.DateTime> DateRented { get; set; }
        public Nullable<System.DateTime> DateReturned { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Movies Movies { get; set; }
    }
}
