//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFirstEntityTesting.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movies()
        {
            this.RentedMovies = new HashSet<RentedMovies>();
        }
    
        public int MovieID { get; set; }
        public string Rating { get; set; }
        public string Title { get; set; }
        public string Year { get; set; }
        public Nullable<decimal> Rental_Cost { get; set; }
        public string Copies { get; set; }
        public string Plot { get; set; }
        public string Genre { get; set; }
        public byte[] IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentedMovies> RentedMovies { get; set; }
    }
}
